#!/usr/bin/env python3
# ruff: noqa: E501
"""Generate or check the portable Brief-Spec verification truth boundary."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "release" / "truth-boundary.json"
DESTINATION = ROOT / "docs" / "verification.md"


def _maturity_rows(values: dict[str, str]) -> str:
    return "\n".join(f"| {name} | `{maturity}` |" for name, maturity in values.items())


def _live_rows(values: dict[str, dict[str, object]]) -> str:
    return "\n".join(
        f"| {name} | {record['passed']}/{record['required']} | `{record['evidence']}` |"
        for name, record in values.items()
    )


def render(value: dict[str, object]) -> str:
    ci = value["hosted_ci"]
    publication = value["publication"]
    local = value["local_evidence"]
    artifacts = value["candidate_artifacts"]
    rollout = value["local_rollout"]
    optional = value["optional_gates"]
    schemas = value["schemas"]
    maturity = value["host_maturity"]
    live = value["live_e2e"]
    live_authorization = value["live_e2e_authorization"]
    gates = value["account_gates"]
    assert isinstance(ci, dict)
    assert isinstance(publication, dict)
    assert isinstance(local, dict)
    assert isinstance(artifacts, dict)
    assert isinstance(rollout, dict)
    assert isinstance(optional, dict)
    assert isinstance(schemas, dict)
    assert isinstance(maturity, dict)
    assert isinstance(live, dict)
    assert isinstance(live_authorization, dict)
    assert isinstance(gates, list)
    gate_lines = "\n".join(f"- {gate}" for gate in gates)
    ci_url = f"https://github.com/{value['repository']}/actions/runs/{ci['run_id']}"
    repository_status = f"Canonical {value['repository_visibility']} repository confirmed"
    global_components = rollout.get("components", "Core plus PDF and audio renderers")
    if ci["steps_executed"]:
        hosted_explanation = (
            "The recorded hosted run executed repository jobs and is real platform evidence. "
            f"It did not authorize release because {ci['blocker']}. The current uncommitted "
            "candidate still requires a new exact-revision hosted run after it is committed."
        )
    else:
        hosted_explanation = (
            "The hosted failure is infrastructure evidence, not repository test evidence: "
            "GitHub rejected the jobs before any step ran because of the recorded "
            f"{ci['blocker']} condition."
        )
    if live_authorization["status"] == "authorized":
        live_gate_statement = "The five required local live-host gates are authorized."
    else:
        live_gate_statement = (
            "The retained five-host matrix remains useful baseline evidence, but exact-current-"
            f"worktree live authorization is `{live_authorization['status']}` because "
            f"{live_authorization['blocker']}."
        )
    return f"""<!-- briefspec:verification:v1 version={value["version"]} -->
<!-- Generated by scripts/generate-verification.py; do not edit by hand. -->
# Brief-Spec {value["version"]} verification truth boundary

Updated: `{value["updated_at"]}`
Source basis: `{value["source_revision"]}`
Canonical repository: [github.com/{value["repository"]}](https://github.com/{value["repository"]})

This document separates implementation, validation, host evidence, and publication. A local or
globally installed candidate is not a public release.

## Current state

| Boundary | Evidence | Status |
| --- | --- | --- |
| Source candidate | Version `{value["version"]}` derived from `{value["source_revision"]}` | {value["candidate_state"]} |
| Repository | `{value["repository_visibility"]}` canonical repository | {repository_status} |
| Latest GitHub release | `{value["latest_public_release"]}` | Published historical release |
| Local gates | {local["tests"]} tests, {local["release_checks"]} source checks, {local["wheel_release_checks"]} wheel checks, {local["coverage_percent"]}% coverage on {local["platform"]} / Python {local["python"]} | {local["current_state"]} |
| Hosted CI | [run {ci["run_id"]}]({ci_url}) for `{ci["revision"]}` | {ci["status"]}; steps executed: `{str(ci["steps_executed"]).lower()}` |
| Live harness evidence | Sanitized disposable-repository results retained locally | {value["host_live_evidence"]} |
| Live release authorization | `{live_authorization["evidence"]}`; source fingerprint `{live_authorization["source_worktree_fingerprint"]}` | {live_authorization["status"]} by `{live_authorization["blocker"]}` |
| GitHub `v0.5.0` | Release API and workflow state | {publication["github_release"]} |
| PyPI core/PDF/audio | PyPI project/file lookup | {publication["pypi_core"]} / {publication["pypi_pdf"]} / {publication["pypi_audio"]} |
| PyPI Chronicle/video | Independent extension project/file lookup | {publication.get("pypi_chronicle", "not-published")} / {publication.get("pypi_video", "not-published")} |
| Canonical schemas | `{schemas["namespace"]}` plus `{schemas["offline_bundle"]}` | {"published" if schemas["published"] else "built locally; not published"} |

{hosted_explanation} {live_gate_statement} Public release remains blocked on the exact-SHA live,
hosted, and account-owned publication gates.

## Harness evidence tiers

| Harness | Current claim |
| --- | --- |
{_maturity_rows(maturity)}

`live-verified` means the deterministic installation controls and required authenticated matrix
passed for the retained `0.5.0` adapter baseline. It does not override the exact-worktree freshness
status above. `hold` is a visible unresolved condition. `experimental` is best effort and
non-blocking.

## Retained live-host matrix

| Harness | Passed/required | Local sanitized summary |
| --- | ---: | --- |
{_live_rows(live)}

Every passing scenario required the host hook, bounded contract, strict validation, equivalent
deterministic downloads, bundle and receipt verification, and an authorized-change check. The
summaries retain metadata and hashes, not credentials or raw transcripts. Grok's native gate uses
passive classification hooks, one bounded Stop repair, and a native read/edit allowlist in a
disposable repository; shell, web, memory, and subagents remain disabled.

The committed evidence file contains only sanitized decisions, artifact hashes, categorical failure
reasons, and hashed opaque session references. CI recomputes its release-source fingerprint and the
release authorization fails closed unless all required hosts pass.

## Candidate artifacts and rollout

| Boundary | Retained evidence | Status |
| --- | --- | --- |
| Distribution set | `{artifacts["directory"]}`; manifest `{artifacts["release_manifest_sha256"]}` | {artifacts["state"]} |
| Core wheel | SHA-256 `{artifacts["core_wheel_sha256"]}` | Installed globally from these exact bytes |
| Offline schemas | SHA-256 `{artifacts["schema_bundle_sha256"]}` | Built and validated locally; not published |
| Global tool | {global_components} | {rollout["global"]} |
| Global doctors | User and detected project scopes | {rollout["doctors"]} |
| Intentional overrides | Receipt-owned paths only | {rollout["project_overrides"]} |
| Rollback | Byte-for-byte manifest verification | {rollout["rollback"]} |

The artifact manifest intentionally has no hosted source authorization: these bytes came from an
uncommitted local worktree. Hosted CI must rebuild once from the exact committed revision and the
release workflow must reuse those hosted bytes unchanged.

## Browser and optional-renderer gates

| Gate | Local result |
| --- | --- |
| Self-contained HTML | {optional["browser"]} |
| Playwright PDF | {optional["pdf"]} |
| Offline macOS audio | {optional["local_macos_audio"]} |
| Offline Chronicle video | {optional.get("video", "Not run")} |
| Explicit-consent OpenAI audio | {optional["openai_audio"]} |

## Candidate trust corrections validated locally

- honest classification with negation masking, abstention, decision records, and reported-marker
  downgrade;
- zero-network and no-plugin verification defaults, SSRF-safe public-address policy, bounded files
  and archives, and no command execution;
- receipt-hash ownership with preservation of locally modified skills;
- deterministic runtime precedence and hermetic no-CLI/fake-CLI test lanes;
- status-first human renderings, portable release-hosted schemas, and an offline schema bundle;
- exact-SHA CI authorization that reuses tested bytes and blocks tag-time rebuilding;
- evidence-based harness maturity, with a retained full baseline for all five required hosts and
  an explicit exact-worktree freshness boundary.

## Account-owned release gates

{gate_lines}

The repository-owned implementation may prepare these gates but cannot truthfully mark them complete.
The release workflow must consume the exact candidate artifact produced by successful CI, publish
identical bytes through Trusted Publishing, verify PyPI/GitHub digests, then finalize GitHub.

Historical `v0.1.0` evidence remains in
[`verification-v0.1.0.md`](verification-v0.1.0.md) and is never promoted to current evidence.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(json.loads(SOURCE.read_text(encoding="utf-8")))
    if args.check:
        actual = DESTINATION.read_text(encoding="utf-8") if DESTINATION.is_file() else ""
        if actual != expected:
            raise SystemExit("docs/verification.md is stale; run scripts/generate-verification.py")
        return 0
    DESTINATION.write_text(expected, encoding="utf-8")
    print(DESTINATION)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
