"""Stable versions, tokens, and exit codes."""

from __future__ import annotations

from pathlib import Path


def _load_version() -> str:
    here = Path(__file__).resolve()
    candidates = (
        here.parents[2] / "VERSION",
        here.parent / "assets" / "VERSION",
    )
    for path in candidates:
        try:
            text = path.read_text(encoding="utf-8").strip()
        except OSError:
            continue
        if text:
            return text
    return ""


VERSION = _load_version()
ENVELOPE_VERSION = 1
SEAM_MAP_VERSION = 1
DELIVERY_PLAN_VERSION = 1
TASK_GRAPH_VERSION = 1

EXIT_OK = 0
EXIT_NEEDS_INPUT = 2
EXIT_INVALID = 3
EXIT_CONFLICT = 4
EXIT_UNAVAILABLE = 5
EXIT_INTERNAL = 10

SEAM_READY = "SEAM_MAP=READY"
SEAM_NEEDS_DISCOVERY = "SEAM_MAP=NEEDS_DISCOVERY"
SEAM_NEEDS_OWNER = "SEAM_MAP=NEEDS_OWNER_INPUT"
SEAM_NEEDS_DECISION = "SEAM_MAP=NEEDS_ARCHITECTURE_DECISION"
SEAM_AMBIGUOUS = "SEAM_MAP=AMBIGUOUS"
SEAM_ERROR = "SEAM_MAP=ERROR"

PLAN_READY = "DELIVERY_PLAN=READY"
PLAN_NEEDS_REVIEW = "DELIVERY_PLAN=NEEDS_REVIEW"
PLAN_OPEN_OBJECTIONS = "DELIVERY_PLAN=OPEN_OBJECTIONS"
PLAN_NEEDS_OWNER = "DELIVERY_PLAN=NEEDS_OWNER_INPUT"
PLAN_NEEDS_DECISION = "DELIVERY_PLAN=NEEDS_ARCHITECTURE_DECISION"
PLAN_ERROR = "DELIVERY_PLAN=ERROR"

GRAPH_READY = "TASK_GRAPH=READY"
GRAPH_CYCLE = "TASK_GRAPH=CYCLE"
GRAPH_COLLISION = "TASK_GRAPH=COLLISION"
GRAPH_UNPROVABLE = "TASK_GRAPH=UNPROVABLE_NODE"
GRAPH_BLOCKED = "TASK_GRAPH=BLOCKED"
GRAPH_ERROR = "TASK_GRAPH=ERROR"

INIT_READY = "WORKSPACE=READY"
STATUS_READY = "STATUS=READY"
STATUS_BLOCKED = "STATUS=BLOCKED"
DOCTOR_OK = "DOCTOR=OK"
DOCTOR_BLOCKED = "DOCTOR=BLOCKED"
INSTALL_OK = "INSTALL=OK"
UNINSTALL_OK = "UNINSTALL=OK"
REPORT_READY = "REPORT=READY"
CONTEXT_READY = "AGENT_CONTEXT=READY"
