#!/usr/bin/env python3
"""Print the stable machine-facing Task-Spec CLI contract."""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
VERSION = (ROOT / "VERSION").read_text(encoding="utf-8").strip()

commands = {
    "init": {"mutation": "creates missing tasks/ and .taskspec/config", "tokens": ["INIT=OK", "INIT=DRY_RUN"]},
    "setup": {"mutation": "none", "tokens": ["SETUP=READY"]},
    "setup signing": {"mutation": "creates or explicitly rotates the repository-private HMAC key", "tokens": []},
    "demo": {"mutation": "creates and removes an isolated temporary repository", "tokens": ["DEMO=READY", "DEMO=DRY_RUN"]},
    "example": {"mutation": "writes one installed canonical example non-clobberingly; --force replaces and --dry-run writes nothing", "tokens": ["EXAMPLE=WRITTEN", "EXAMPLE=DRY_RUN", "EXAMPLE=REFUSED"]},
    "new": {"mutation": "creates one Task-Spec scaffold and derived state", "tokens": []},
    "plan": {"mutation": "none", "tokens": ["TASK_PLAN=OK", "TASK_PLAN=INVALID"]},
    "batch": {"mutation": "creates declared Task-Spec scaffolds; --dry-run writes nothing", "tokens": ["TASK_BATCH=OK", "TASK_BATCH=DRY_RUN", "TASK_BATCH=REFUSED"]},
    "migrate": {"mutation": "atomically upgrades one explicitly named legacy task under the task-state lock", "tokens": []},
    "validate": {"mutation": "refreshes deterministic derived state unless --no-state", "tokens": []},
    "dod": {"mutation": "none", "tokens": ["DOD=COMPLETE", "DOD=GAPS"]},
    "gate": {"mutation": "--stamp writes the sign-off envelope; otherwise none", "tokens": ["TIER=1", "TIER=2"]},
    "handoff": {"mutation": "stdout is read-only; --out writes non-clobberingly unless --force", "tokens": ["HANDOFF=WRITTEN", "HANDOFF=INVALID", "HANDOFF=REFUSED"]},
    "run": {"mutation": "runs declared eval commands in the task workspace", "tokens": []},
    "accept": {"mutation": "--stamp atomically writes AcceptanceRecord/v1 plus the complete acceptance envelope", "tokens": ["ACCEPTED=1", "ACCEPTED=0", "ACCEPTANCE_FAILURE=<code>"]},
    "author-doctor": {"mutation": "none", "tokens": ["AUTHOR_DOCTOR=READY", "AUTHOR_DOCTOR=INVALID"]},
    "holdout": {"mutation": "seal/run may write descriptor or receipt; verify is read-only", "tokens": ["HOLDOUT=SEALED", "HOLDOUT=VERIFIED", "HOLDOUT=INVALID"]},
    "receipt": {"mutation": "creator/sign commands write explicit receipt paths; validate is read-only", "tokens": ["RECEIPT=WRITTEN", "RECEIPT=SIGNED", "RECEIPT=INVALID"]},
    "eval-audit": {"mutation": "uses temporary git worktrees; optional report path", "tokens": ["EVAL_AUDIT=INVALID"]},
    "identity": {"mutation": "init/sign/revoke write explicit files; verify is read-only", "tokens": ["IDENTITY=READY", "IDENTITY=SIGNED", "IDENTITY=VERIFIED", "IDENTITY=REVOKED"]},
    "evidence": {"mutation": "run writes an explicit evidence directory; validate/plan are read-only", "tokens": ["ENGINE_MATRIX=VALID", "ENGINE_MATRIX=INVALID"]},
    "bridge": {"mutation": "export writes only with --out; validate is read-only", "tokens": ["BRIDGE=VALID", "BRIDGE=INVALID"]},
    "dsse": {"mutation": "export writes only to --out; verify is read-only", "tokens": ["DSSE=EXPORTED", "DSSE=VERIFIED", "DSSE=INVALID"]},
    "mcp": {"mutation": "read-only stdio server", "tokens": []},
    "ready": {"mutation": "none", "tokens": []},
    "graph": {"mutation": "none; TaskGraphView/v1 is derived from Markdown and Git", "tokens": ["GRAPH=<digest>", "GRAPH=INVALID"]},
    "status": {"mutation": "none; emits TaskStatus/v1 and exactly one safe next command", "tokens": ["NEXT=<command>", "STATUS=INVALID"]},
    "lint": {"mutation": "none", "tokens": []},
    "transition": {"mutation": "changes lifecycle status and derived state", "tokens": []},
    "rebuild-state": {"mutation": "rewrites deterministic tasks/_state.yaml", "tokens": []},
    "archive": {"mutation": "moves root done/parked tasks under the task-state lock and refreshes derived state", "tokens": []},
    "backup": {"mutation": "writes a timestamped backlog archive to the selected destination", "tokens": []},
    "metrics": {"mutation": "none", "tokens": []},
    "conformance": {"mutation": "self-test uses disposable fixtures only", "tokens": []},
    "executor": {"mutation": "reference L2 executor; transitions, executes, accepts, or parks one supplied task", "tokens": []},
    "agent-context": {"mutation": "none", "tokens": []},
    "completion": {"mutation": "none", "tokens": []},
    "doctor": {"mutation": "none", "tokens": ["BACKLOG_DOCTOR=READY", "BACKLOG_DOCTOR=BLOCKED"]},
    "version": {"mutation": "none", "tokens": []},
    "help": {"mutation": "none", "tokens": []},
}

contract = {
    "contract": "TaskSpecAgentContext/v1",
    "engine_version": VERSION,
    "format_version": 4,
    "default_format_version": 3,
    "supported_format_versions": [1, 2, 3, 4],
    "binary": "taskspec",
    "global_options": {
        "--json": "wrap command stdout/stderr and exit status in one JSON envelope",
        "--dry-run": "prevent supported mutations and report intended action",
        "NO_COLOR": "disable ANSI color when present",
        "TASKSPEC_COLOR": "0 disables and 1 forces ANSI color",
    },
    "exit_codes": {"0": "success", "1": "validation, gate, eval, or acceptance failure", "2": "usage error", "3": "unsupported runtime requirement"},
    "commands": commands,
    "contracts": {
        "task_spec": "spec/schemas/task-spec-frontmatter.schema.json",
        "task_plan": "spec/schemas/task-plan.schema.json",
        "task_materialization_receipt": "spec/schemas/task-materialization-receipt.schema.json",
        "task_handoff": "spec/schemas/task-handoff.schema.json",
        "task_revision": "spec/schemas/task-revision.schema.json",
        "task_graph_view": "spec/schemas/task-graph-view.schema.json",
        "task_status": "spec/schemas/task-status.schema.json",
        "receipt_subject": "spec/schemas/receipt-subject.schema.json",
        "acceptance_record": "spec/schemas/acceptance-record.schema.json",
        "acceptance_finalized": "spec/schemas/acceptance-finalized.schema.json",
        "acceptance_failure": "spec/schemas/acceptance-failure.schema.json",
        "evaluator_trust": "spec/schemas/evaluator-trust.schema.json",
        "mutation_matrix": "spec/schemas/mutation-matrix.schema.json",
        "provider_smoke_evidence": "spec/schemas/provider-smoke-evidence.schema.json",
        "authoring_evidence": "spec/schemas/authoring-evidence.schema.json",
        "evaluation_receipt": "spec/schemas/evaluation-receipt.schema.json",
        "graded_evaluation_receipt": "spec/schemas/graded-evaluation-receipt.schema.json",
        "human_acceptance_receipt": "spec/schemas/human-acceptance-receipt.schema.json",
        "environment_contract": "spec/schemas/environment-contract.schema.json",
        "environment_receipt": "spec/schemas/environment-receipt.schema.json",
        "authorization_receipt": "spec/schemas/authorization-receipt.schema.json",
        "engine_run_receipt": "spec/schemas/engine-run-receipt.schema.json",
        "holdout_bundle": "spec/schemas/holdout-bundle.schema.json",
        "holdout_descriptor": "spec/schemas/holdout-descriptor.schema.json",
        "agent_contract": "spec/schemas/agent-contract.schema.json",
        "a2a_artifact": "spec/schemas/a2a-artifact.schema.json",
        "mcp_task": "spec/schemas/mcp-task.schema.json",
    },
    "credentials": "TaskHandoff and AgentContext never contain credentials; provider and model credentials remain external to core.",
}

print(json.dumps(contract, indent=2, ensure_ascii=False))
