#!/usr/bin/env python3
"""Render a CLI reference from the canonical command matrix, or prove it can."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
MATRIX = ROOT / "contracts" / "cli-command-matrix.json"
OUTPUT = ROOT / "docs" / "reference" / "cli.md"


def render() -> str:
    matrix = json.loads(MATRIX.read_text(encoding="utf-8"))
    commands = matrix["commands"]
    if matrix.get("contract") != "ConvergeCLICommandMatrix/v1":
        raise ValueError("unexpected matrix contract")
    if matrix.get("command_count") != len(commands):
        raise ValueError("matrix command_count does not match commands")
    lines = [
        "<!-- GENERATED by scripts/render-cli-reference.py. Edit contracts/cli-command-matrix.json. -->",
        "# Converge CLI reference",
        "",
        "Status: canonical command reference for Converge 0.2.0.",
        "",
        "Every form accepts `--json` and `--dry-run` in any position. `--json` emits one",
        "`ConvergeCLIResult/v1` document and preserves the command exit code. `--dry-run`",
        "prevents mutations; read-only commands still execute.",
        "",
        f"Declared public forms: **{len(commands)}**.",
        "",
    ]
    for command in commands:
        tokens = ", ".join(f"`{token}`" for token in command["emits_tokens"]) or "None"
        lines.extend(
            [
                f"## `{command['name']}`",
                "",
                command["description"],
                "",
                f"- Mutates: **{'yes' if command['mutating'] else 'no'}**",
                f"- Converge pass: `{command['converge_pass']}`",
                f"- Delegates to: `{command['wraps']}`",
                f"- Tokens: {tokens}",
                f"- Example: `{command['example']}`",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if actual != expected:
            print("CLI_REFERENCE=STALE", file=sys.stderr)
            return 1
        print("CLI_REFERENCE=READY")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"WROTE {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
