#!/usr/bin/env bash
# rebuild-state.sh — Regenerate tasks/_state.yaml from frontmatter scan.
#
# This is the recovery script. If _state.yaml is corrupt or out-of-sync,
# run this to rebuild it from the authoritative source (frontmatter).
#
# Safe to run anytime. Non-destructive. Always converges.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/_lib.sh
source "$SCRIPT_DIR/../lib/_lib.sh"
ts_version_flag "$@"

TASKS_DIR="$TASKSPEC_BACKLOG_DIR"
STATE_FILE="${TASKS_DIR}/_state.yaml"

if [[ ! -d "$TASKS_DIR" ]]; then
  echo "ERROR: no $TASKS_DIR/ directory found in $(pwd)" >&2
  exit 1
fi

LOCK_FILE="$TASKS_DIR/.state.lock"
if [[ "${TASKSPEC_STATE_LOCK_HELD:-0}" != "1" ]]; then
  if ! ts_lock_acquire "$LOCK_FILE"; then
    echo "taskspec rebuild-state: another process holds the task-state lock" >&2
    exit 1
  fi
  trap 'ts_lock_release "$LOCK_FILE"' EXIT
fi

# A derived index must be reproducible. Use the latest canonical lifecycle
# timestamp already present in tasks or the event ledger, never the wall clock
# of the rebuild itself.
TS="$(
  {
    find "$TASKS_DIR" -type f -name 'T-*.md' -exec \
      sed -n -E 's/^(created|signed_off_at|accepted_at):[[:space:]]*//p' {} \; 2>/dev/null
    if [[ -f "$TASKS_DIR/_metrics.jsonl" ]]; then
      sed -n -E 's/.*"ts":"([^"]+)".*/\1/p' "$TASKS_DIR/_metrics.jsonl"
    fi
  } | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}T' | LC_ALL=C sort | tail -1 || true
)"
[[ -n "$TS" ]] || TS="1970-01-01T00:00:00Z"
WORKSPACE_ROOT="$(ts_workspace_root "$TASKS_DIR")"
STATE_GENERATOR="${TASKSPEC_STATE_GENERATOR:-rebuild-state.sh}"
STATE_VALIDATOR_VERSION="${TASKSPEC_STATE_VALIDATOR_VERSION:-rebuild}"
GRAPH_REVISION="$(python3 "$TASKSPEC_SKILL_DIR/src/graph/task_graph.py" --backlog "$TASKS_DIR" --json \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["graph_revision_digest"])')"

TMP="${STATE_FILE}.tmp.$$"
ts_prepare_tmp "$TMP"

{
  echo "# Auto-generated by $STATE_GENERATOR — DO NOT EDIT DIRECTLY"
  echo "# Source of truth: frontmatter in each tasks/T-*.md"
  echo "schema_version: 1"
  echo "last_rebuilt: $TS"
  echo "graph_revision_digest: $GRAPH_REVISION"
  echo ""
  echo "tasks:"
} > "$TMP"

READY=()
IN_PROGRESS=()
BLOCKED=()
DONE=()
PARKED=()

TOTAL=0

# Scan every T-*.md anywhere under tasks/ (root + queue/ + done/ + parked/ +
# skill/ + kimi/ + feature/ + archive/ + any future subdir). Recursive find so
# new task folders are indexed automatically without editing this script.
while IFS= read -r FILE; do
  [[ -f "$FILE" ]] || continue

  ID=$(grep '^id:' "$FILE" | head -1 | awk '{print $2}' || echo "")
  STATUS=$(grep '^status:' "$FILE" | head -1 | awk '{print $2}' || echo "unknown")
  EFFORT=$(grep '^effort:' "$FILE" | head -1 | awk '{print $2}' || echo "?")
  AGENT=$(grep '^agent:' "$FILE" | head -1 | awk '{print $2}' || echo "any")

  [[ -z "$ID" ]] && continue

  TOTAL=$((TOTAL + 1))

  {
    echo "- id: ${ID}"
    FILE_ABS="$(cd "$(dirname "$FILE")" && pwd)/$(basename "$FILE")"
    case "$FILE_ABS" in
      "$WORKSPACE_ROOT"/*) DISPLAY_FILE="${FILE_ABS#"$WORKSPACE_ROOT"/}" ;;
      *) DISPLAY_FILE="$FILE" ;;
    esac
    echo "  path: ${DISPLAY_FILE}"
    echo "  status: ${STATUS}"
    echo "  effort: ${EFFORT}"
    echo "  last_validated: ${TS}"
    echo "  validator_version: ${STATE_VALIDATOR_VERSION}"
  } >> "$TMP"

  case "$STATUS" in
    ready) READY+=("$ID") ;;
    in-progress) IN_PROGRESS+=("$ID") ;;
    blocked) BLOCKED+=("$ID") ;;
    done) DONE+=("$ID") ;;
    parked) PARKED+=("$ID") ;;
  esac
done < <(find "$TASKS_DIR" -type f -name 'T-*.md' | sort)

{
  echo ""
  echo "ready_queue:"
  for id in "${READY[@]:-}"; do [[ -n "$id" ]] && echo "  - $id"; done

  echo ""
  echo "in_progress:"
  for id in "${IN_PROGRESS[@]:-}"; do [[ -n "$id" ]] && echo "  - $id"; done

  echo ""
  echo "blocked:"
  for id in "${BLOCKED[@]:-}"; do [[ -n "$id" ]] && echo "  - $id"; done

  echo ""
  echo "stats:"
  echo "  total: $TOTAL"
  echo "  ready: ${#READY[@]}"
  echo "  in_progress: ${#IN_PROGRESS[@]}"
  echo "  blocked: ${#BLOCKED[@]}"
  echo "  done: ${#DONE[@]}"
  echo "  parked: ${#PARKED[@]}"
} >> "$TMP"

mv "$TMP" "$STATE_FILE"

echo ">>> Rebuilt $STATE_FILE"
echo "    total: $TOTAL | ready: ${#READY[@]} | in_progress: ${#IN_PROGRESS[@]} | blocked: ${#BLOCKED[@]} | done: ${#DONE[@]} | parked: ${#PARKED[@]}"
